package codebots.gameobjects;

public enum FunctionType {
    SELECT_MESSAGE_RECIPIENTS,
    SEND_MESSAGE,
    PROCESS_MESSAGE,
    SELECT_ATTACK_TARGET,
    READ_DATA,
    SELECT_FUNCTION_TO_REPLACE,
    SELECT_FUNCTION_TO_BLOCK,
    GET_FLAG
}
